# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 08:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_id', models.IntegerField(default=0)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'bp_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.CharField(max_length=255)),
                ('msisdn', models.CharField(max_length=50)),
                ('amount', models.IntegerField(default=0)),
                ('trx_status', models.IntegerField(default=-1)),
                ('trx_id', models.CharField(max_length=255)),
                ('channel', models.IntegerField(default=1)),
                ('transaction_desc', models.TextField()),
                ('mpesa_txt_date', models.DateTimeField()),
                ('mpesa_trx_id', models.CharField(max_length=50)),
                ('return_code', models.CharField(max_length=10)),
                ('mpesa_desc', models.CharField(max_length=255)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('process_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bp_transaction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('email_address', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('physical_address', models.CharField(max_length=200)),
                ('api_key', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'bp_vendor',
                'managed': False,
            },
        ),
    ]
